---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    name: frontend
spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: http
  selector:
    app: frontend
